### ISSUE TITLE
Project Status - Couldn't find it on the Marketplace 

### ISSUE THREAD

**Issue by kumarharsh** [jbachhardie/vscode-flow-ls#2]
Hi @jbachhardie. I found this from one of your comments in the flow-for-vscode repo. I tried searching for it in the extension marketplace, but it came out empty. Is this published on the marketplace? Also, it this project actively maintained, or is it superseded by the LSP in flow-for-vscode (asking because that one still doesn't work well under Windows).

**Comment by jbachhardie** [comment]
It's here: https://marketplace.visualstudio.com/items?itemName=jbachhardie.flow-ls 😄 

As for maintenance, I'd ideally like to rebase all my improvements here onto `flow-for-vscode` but that isn't as straightforward as just fixing the issues that come up for my colleagues and I (we use Windows as well) in this repository so it will likely remain divergent in the short and medium term.

**Comment by kumarharsh** [comment]
Aah, I missed it in the listing 😒 I guess having an icon helps 😄  I'll give it a try.

**Comment by kumarharsh** [comment]
From my limited testing, the extension runs well on Windows - it takes some time (~4-5 mins) to scan my project, but then it works. It doesn't spawn 15-20 flow processes. 

One drawback for me was that this extension expects the `.flowconfig` file to be in the root of the workspace, which is not the case for me. Is this something which this extension can control, or does the `flow-language-server` handle this?

Also, when I opened the subfolder directly in vscode, flow-language-server kept logging that it couldn't find the `flow-bin` package, even when it was there. It's because it was not looking in my node_modules folder. Perhaps this can be controlled with a config option?

**Comment by jbachhardie** [comment]
1. The `.flowconfig` expectations are definitely set by this extension. I've been meaning to make it scan the folder tree for config files and spawn a language server for each of them but haven't got around to it yet, sorry.

2. Finding the flow binary is up to the language server and I believe the language server (or rather one of its dependencies) has a bug right now that makes it fail to download the required binary from GitHub when run on Windows. I need to look into either a workaround or fixing it upstream but until then you can just manually download `flow.exe` and put it in the folder that he language server error tells you it expects to find it in.

**Comment by kumarharsh** [comment]
Thanks for the reply.

I took a look at the code for this extension and some of flow-language-server yesterday night. Regarding point 2, I think we can specify some flag to let the flow-language-server use the flow bin from node_modules. I'll take a deeper look on the weekend.

I think I might be able to submit a PR for point 1 if I get time. It'd increase the functionality for me and I would be able to use the extension in my main workflow instead of just toying around in a sandbox-like environment.

**Comment by jbachhardie** [comment]
PRs are very welcome.

For the one-server-per-flowconfig feature check out the [multi-server example by Microsoft](https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-multi-server-sample/client/src/extension.ts). That one is one-server-per-workspace-folder instead but the basic principle would be the same.
